"""
Django settings for kalkal project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j+#7+zmsp%a(i!4wf75m6t6)@qj0gt!#@p+fk-0zd(_p@+jy4d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'easy_select2',
    'tinymce',
    'easy_thumbnails',
    'image_cropping',
    # 'captcha',
    'colorful',
    'django_select2',
    'solo',

    'utils',
    'account',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'kalkal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'utils.context_processors.default_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'kalkal.wsgi.application'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
        'null': {
            'class': 'logging.NullHandler',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'py.warnings': {
            'handlers': ['console'],
        },
    }
}


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "../static_root/kalkal")

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

AUTH_USER_MODEL = 'account.Profile'


# SELECT2
AUTO_RENDER_SELECT2_STATICS = False

IMAGE_CROPPING_JQUERY_URL = STATIC_URL + "grappelli/jquery/jquery-2.1.4.min.js"

# captcha
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs',)
CAPTCHA_LENGTH = 5
CAPTCHA_FONT_SIZE = 30
CAPTCHA_TIMEOUT = 80  # minutes
CAPTCHA_BACKGROUND_COLOR = '#000000'
CAPTCHA_FOREGROUND_COLOR = '#ffffff'


# GRAPPELLI SETTINGS
GRAPPELLI_ADMIN_TITLE = "پنل مدیریت سایت کل کل"

TINYMCE_DEFAULT_CONFIG = {
    'plugins': "table,spellchecker,paste,searchreplace",
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 10,
    'theme': "advanced",
    'theme_advanced_toolbar_location': "top"
}

from easy_thumbnails.conf import Settings as thumbnail_settings

THUMBNAIL_PROCESSORS = (
                           'image_cropping.thumbnail_processors.crop_corners',
                       ) + thumbnail_settings.THUMBNAIL_PROCESSORS
THUMBNAIL_DEBUG = False

SELECT2_USE_BUNDLED_JQUERY = False

# DEFAULT_FROM_EMAIL = 'kalkal.irfa@gmail.com'
# SERVER_EMAIL = 'kalkal.irfa@gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'kalkal.irfa@gmail.com'
# EMAIL_HOST_PASSWORD = 'kalkal.irfa1378'

# EMAIL_BACKEND = 'djcelery_email.backends.CeleryEmailBackend'
# DEFAULT_FROM_EMAIL = 'noreply@manzoom.ir'
# SERVER_EMAIL = 'noreply@manzoom.ir'
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'localhost'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'noreply@manzoom.ir'
# EMAIL_HOST_PASSWORD = 'DownWithUSA'

SITE_VERSION = "1.0.18"

LAST_APP_VERSION = '0.0.2'

ENABLE_SITE = True

try:
    from .prk_set import *
except ImportError:
    pass
